export const EDIT_FORM_ACTIONS = {
	NAME_CHANGED: 'NAME_CHANGED',
	USERNAME_CHANGED: 'USERNAME_CHANGED',
	ACTIVE_CHANGED: 'ACTIVE_CHANGED',
	ROLE_CHANGED: 'ROLE_CHANGED',
	USERNAME_ERROR_CHANGED: 'USERNAME_ERROR_CHANGED',
	REPLACE: 'REPLACE'
};
