export const FILTERS_ACTIONS = {
	SEARCH_CHANGED: 'SEARCH_CHANGED',
	ONLY_ACTIVE_CHANGED: 'ONLY_ACTIVE_CHANGED',
	SORT_BY_CHANGED: 'SORT_BY_CHANGED',
	PAGE_CHANGED: 'PAGE_CHANGED',
	ITEMS_PER_PAGE_CHANGED: 'ITEMS_PER_PAGE_CHANGED',
	RESET_FILTERS: 'RESET_FILTERS'
};
